//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilyaMagaza
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobilyalarBilgi
    {
        public int MobilyaNo { get; set; }
        public string MobilyaAdi { get; set; }
        public string MobilyaHammaddesi { get; set; }
        public int MusteriNo { get; set; }
    }
}
