//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilyaMagaza
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusterilerBilgi
    {
        public int MusteriNo { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string MusteriAdres { get; set; }
        public string MusteriTelefon { get; set; }
    }
}
