//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilyaMagaza
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzelliklerBilgi
    {
        public int OzellikNo { get; set; }
        public string MobilyaGrubu { get; set; }
        public string MobilyaRenk { get; set; }
        public string Mensei { get; set; }
        public int MobilyaNo { get; set; }
    }
}
